### ISSUE TITLE
about the GAR best query

### ISSUE THREAD

**Issue by yzc111** [voidism/EAR#1]
Hello, I am interested in your work, but I have some questions about your paper, for example, GAR best query which uses the ground truth label. I actually don't know the detail about this.  use BM25 will get a similar score  between the query expansions with Wikipedia, and then how can I get the best query with ground truth?

**Comment by voidism** [comment]
Hi! Thanks for the question!

For GAR best query, we did BM25 to retrieve the top-100 passages by each query separately. And then we use the ground truth label (the answer span) to check which passages contain the answer. We find the query that has its top-k passage containing the answer with the smallest k. And it is the GAR best query.
The GAR best query will be considered as the performance upper bound of our method.

Hope the above explanation answers your question!

Yung-Sung
